[pytest]
testpaths = apps/analysis_api/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = apps/analysis_api/src
asyncio_mode = auto
addopts = --asyncio-mode=auto
