"""Add input tables: price_data, companies, sectors, markets, panels

Revision ID: e4ecd0c81d29
Revises: ecb5692dd22d
Create Date: 2025-12-13 17:29:06.973693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ecd0c81d29'
down_revision: Union[str, Sequence[str], None] = 'ecb5692dd22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('market_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('market_id'),
    sa.UniqueConstraint('market_name')
    )
    op.create_table('panels',
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('panel_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('panel_id'),
    sa.UniqueConstraint('panel_name')
    )
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.Text(), nullable=True),
    sa.Column('sector_name_en', sa.Text(), nullable=True),
    sa.Column('us_sector', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sector_id'),
    sa.UniqueConstraint('sector_name')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.market_id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.panel_id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.sector_id'], ),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('ticker')
    )
    op.drop_index('idx_historical_scores_symbol_time', table_name='historical_scores')
    op.drop_index('idx_historical_scores_timeframe', table_name='historical_scores')
    op.drop_table('historical_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_scores',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), nullable=False),
    sa.Column('trend_score', sa.NUMERIC(precision=5, scale=3), nullable=False),
    sa.Column('trend_confidence', sa.NUMERIC(precision=5, scale=3), nullable=False),
    sa.Column('momentum_score', sa.NUMERIC(precision=5, scale=3), nullable=False),
    sa.Column('momentum_confidence', sa.NUMERIC(precision=5, scale=3), nullable=False),
    sa.Column('combined_score', sa.NUMERIC(precision=5, scale=3), nullable=False),
    sa.Column('combined_confidence', sa.NUMERIC(precision=5, scale=3), nullable=False),
    sa.Column('trend_weight', sa.NUMERIC(precision=4, scale=3), nullable=False),
    sa.Column('momentum_weight', sa.NUMERIC(precision=4, scale=3), nullable=False),
    sa.Column('trend_signal', sa.VARCHAR(length=20), nullable=False),
    sa.Column('momentum_signal', sa.VARCHAR(length=20), nullable=False),
    sa.Column('combined_signal', sa.VARCHAR(length=20), nullable=False),
    sa.Column('recommendation', sa.VARCHAR(length=20), nullable=False),
    sa.Column('action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('price_at_analysis', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', 'timeframe', name='unique_score_entry')
    )
    op.create_index('idx_historical_scores_timeframe', 'historical_scores', ['timeframe'], unique=False)
    op.create_index('idx_historical_scores_symbol_time', 'historical_scores', ['symbol', 'timestamp'], unique=False)
    op.drop_table('companies')
    op.drop_table('sectors')
    op.drop_table('price_data')
    op.drop_table('panels')
    op.drop_table('markets')
    # ### end Alembic commands ###
