#!/usr/bin/env python3
"""
Generate SQL to insert an admin user using a securely-provided password (read from env var or prompt).
This script DOES NOT connect to the DB. It writes an SQL file with a hashed password (PBKDF2-HMAC-SHA256)
that you can inspect and run with `psql` or another DB client.

Usage:
  ADMIN_PASSWORD="..." python scripts/generate_admin_sql.py --username admin --email admin@example.com --out admin_insert.sql

Do NOT store ADMIN_PASSWORD in files. Prefer reading it from your vault into the environment for the single-run.
"""

import argparse
import binascii
import hashlib
import os
import secrets
from datetime import datetime

SALT_BYTES = 16
ITERATIONS = 200_000


def hash_password(password: str, salt: bytes | None = None):
    if salt is None:
        salt = secrets.token_bytes(SALT_BYTES)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, ITERATIONS)
    return dk, salt


def make_insert_sql(
    username: str,
    email: str,
    hashed_hex: str,
    salt_hex: str,
    now_iso: str,
    table_name: str = "users",
):
    # Adapt column names as necessary for your schema. This example assumes columns:
    # (username, email, password_hash, password_salt, is_admin, created_at)
    sql = f"""
-- Generated by scripts/generate_admin_sql.py at {now_iso}
INSERT INTO {table_name} (username, email, password_hash, password_salt, is_admin, created_at)
VALUES (
  '{username.replace("'", "''")}',
  '{email.replace("'", "''")}',
  '\\x{hashed_hex}',
  '\\x{salt_hex}',
  true,
  '{now_iso}'
);
"""
    return sql


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--username", required=True)
    p.add_argument("--email", required=True)
    p.add_argument("--out", required=True, help="Output SQL file path")
    p.add_argument("--table", default="users", help="Users table name")
    args = p.parse_args()

    pw = os.getenv("ADMIN_PASSWORD")
    if not pw:
        # Do not echo password; read from stdin safely
        try:
            import getpass

            pw = getpass.getpass("ADMIN_PASSWORD (will not echo): ")
        except Exception:
            raise SystemExit("ADMIN_PASSWORD env var not set and getpass failed")

    dk, salt = hash_password(pw)
    hashed_hex = binascii.hexlify(dk).decode("ascii")
    salt_hex = binascii.hexlify(salt).decode("ascii")
    now_iso = datetime.utcnow().isoformat() + "Z"

    sql = make_insert_sql(
        args.username, args.email, hashed_hex, salt_hex, now_iso, table_name=args.table
    )

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Wrote SQL to {args.out}. Inspect before running.")


if __name__ == "__main__":
    main()
